### ISSUE TITLE
TokenFlow Integration Enrichers Depend on Deprecated API

### ISSUE THREAD

**Issue by SpaceKatt** [cmayomsft/domain-specific-entities-node#30]
Recognizers were removed from TokenFlow ([in this commit](https://github.com/MikeHopcroft/TokenFlow/commit/42c5229b650649cc10b73f8bf0c750ce432adf47)), but are still used by the `intentalyzer-tokenflow-integration` package in `npm`.

https://github.com/cmayomsft/domain-specific-entities-node/blob/d0648416970fa9c0d5cebabb9bd296de06b5c323/packages/tokenflow-integration/src/individual-entity-enricher.ts#L3

https://github.com/cmayomsft/domain-specific-entities-node/blob/d0648416970fa9c0d5cebabb9bd296de06b5c323/packages/tokenflow-integration/src/full-utterance-enricher.ts#L2

**Comment by drub0y** [comment]
No longer an issue as of PR #34 .
